StylesPath = .styles
MinAlertLevel = suggestion
Packages = Readability, proselint, write-good

[*.{tex}]
# List of styles to load.
BasedOnStyles = Vale, Readability, proselint, write-good
Vale.Spelling = NO
