name: Compile LaTeX and update release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: write

jobs:
  compile-and-release:
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Compile LaTeX
      #   uses: xu-cheng/latex-action@v3
      #   with:
      #     root_file: main.tex
      #     latexmk_shell_escape: true
      #

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Compile
        run: make install && make build

      - name: Rename PDF
        run: mv main.pdf DawidKarpinski-mgr.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          name: "Master's Thesis"
          tag_name: "latest"
          files: |
            DawidKarpinski-mgr.pdf
