name: Compile LaTeX and update release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: write

jobs:
  compile-and-release:
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install analysis
        run: make install

      - name: Run analysis
        run: |
          source .venv/bin/activate
          make hist-all

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile report
        run: |
          make report

      - name: Rename PDF
        run: mv typst/main.pdf typst/DawidKarpinski-mgr.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          name: "Master's Thesis"
          tag_name: "latest"
          files: |
            typst/DawidKarpinski-mgr.pdf
